"""Query engine service — orchestrates the full RAG pipeline.

Public surface:
  handle_query(conversation, query, request_id, user_id, db, redis_client)
      AsyncGenerator that yields SSE-formatted strings.

SSE event sequence:
  1. ``{"request_id": "<uuid>"}``   — first event, before any processing.
  2. ``{"token": "..."}``           — zero or more token events during streaming.
  3. ``{"done": true, "citations": [...]}``  — terminal success event.

  On cancellation (client called DELETE /{id}/query/{request_id}):
  3. ``{"cancelled": true}``        — terminal; partial response not persisted.

  On retrieval/embedding failure:
  2. ``{"error": "..."}``           — terminal; no messages persisted.

  On LLM streaming failure:
  *after partial tokens*
  ``{"error": "..."}``              — terminal; partial response not persisted.

Design notes:
  - Cancellation is checked between every token by polling Redis for
    ``cancel:{request_id}``.  Polling is cheap (one EXISTS call per token).
  - Messages are persisted ONLY after the full stream completes successfully.
    A cancelled or errored stream does not produce any Message rows.
  - ``_get_recent_history`` fetches the last CONVERSATION_HISTORY_MESSAGES
    rows in reverse order then reverses in Python — avoids a sub-query and
    keeps the ORM usage consistent with the rest of the codebase.
"""
import json
import logging
import uuid
from collections.abc import AsyncGenerator

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.conversations.models import Conversation, Message
from app.conversations.service import append_message
from app.core.config import settings
from app.core.exceptions import ServiceUnavailableError
from app.core.openai_client import stream_chat_completion
from app.query_engine.context import assemble_context, extract_citations
from app.query_engine.prompts import build_system_prompt
from app.retrieval.service import search
from app.shared.enums import MessageRole

logger = logging.getLogger(__name__)

# ── SSE helper ────────────────────────────────────────────────────────────────

def format_sse(data: dict) -> str:
    """Encode *data* as a single SSE message.

    Returns a string of the form ``data: {json}\\n\\n`` which is the standard
    SSE wire format.
    """
    return f"data: {json.dumps(data)}\n\n"


# ── Internal helpers ──────────────────────────────────────────────────────────

async def _get_recent_history(
    conversation: Conversation,
    db: AsyncSession,
) -> list[dict]:
    """Return the last ``CONVERSATION_HISTORY_MESSAGES`` messages as LLM dicts.

    Fetches rows in descending order (most recent first) then reverses them
    so the returned list is chronological (oldest first), which is the order
    the LLM expects.

    Args:
        conversation: The conversation whose history to load.
        db:           Active async database session.

    Returns:
        List of ``{"role": ..., "content": ...}`` dicts suitable for direct
        inclusion in the OpenAI messages list.
    """
    result = await db.execute(
        select(Message)
        .where(Message.conversation_id == conversation.id)
        .order_by(Message.created_at.desc())
        .limit(settings.CONVERSATION_HISTORY_MESSAGES)
    )
    messages = list(result.scalars())
    messages.reverse()  # chronological order
    return [{"role": msg.role, "content": msg.content} for msg in messages]


# ── Main entry point ──────────────────────────────────────────────────────────

async def handle_query(
    conversation: Conversation,
    query: str,
    request_id: uuid.UUID,
    user_id: uuid.UUID,
    db: AsyncSession,
    redis_client,
) -> AsyncGenerator[str, None]:
    """Orchestrate the RAG pipeline and yield SSE-formatted events.

    This is an async generator consumed by the router's ``StreamingResponse``.
    It must yield the ``request_id`` event first so the client can store it
    before any latency-inducing work begins.

    Args:
        conversation:  Verified, user-owned ``Conversation`` ORM object.
        query:         The user's natural language question.
        request_id:    UUID generated by the router for this specific request.
                       Used as the Redis cancellation key (``cancel:{request_id}``).
        user_id:       Caller's user ID; forwarded to the retrieval service for
                       ownership enforcement.
        db:            Active async database session.
        redis_client:  Async Redis client used to poll for cancellation.

    Yields:
        SSE-formatted strings (``data: {...}\\n\\n``).
    """
    # ── 1. Announce request_id immediately ───────────────────────────────────
    yield format_sse({"request_id": str(request_id)})

    # ── 2. Retrieve relevant chunks ──────────────────────────────────────────
    try:
        chunks = await search(
            query=query,
            user_id=user_id,
            domain_id=conversation.domain_id,
            top_k=settings.MAX_CHUNKS_PER_QUERY,
            db=db,
        )
    except ServiceUnavailableError as exc:
        yield format_sse({"error": exc.message})
        return

    # ── 3. Handle empty retrieval ─────────────────────────────────────────────
    if not chunks:
        no_results_msg = (
            "I could not find any relevant documents to answer your question."
        )
        yield format_sse({"token": no_results_msg})
        yield format_sse({"done": True, "citations": []})
        try:
            await append_message(conversation, MessageRole.user, query, None, db)
            await append_message(
                conversation, MessageRole.assistant, no_results_msg, [], db
            )
        except Exception as exc:  # pragma: no cover
            logger.error("Failed to persist no-results messages: %s", exc)
        return

    # ── 4. Assemble context within token budget ───────────────────────────────
    context_text, selected_chunks = assemble_context(chunks, settings.CONTEXT_TOKEN_BUDGET)

    # ── 5. Build LLM messages list ────────────────────────────────────────────
    history = await _get_recent_history(conversation, db)
    system_prompt = build_system_prompt(context_text)

    llm_messages: list[dict] = [{"role": "system", "content": system_prompt}]
    llm_messages.extend(history)
    llm_messages.append({"role": "user", "content": query})

    # ── 6. Stream LLM response ────────────────────────────────────────────────
    full_response_parts: list[str] = []
    try:
        async for token in stream_chat_completion(llm_messages):
            # Poll Redis cancellation flag between tokens.
            if await redis_client.exists(f"cancel:{request_id}"):
                yield format_sse({"cancelled": True})
                return  # Do NOT persist partial response.
            yield format_sse({"token": token})
            full_response_parts.append(token)
    except Exception as exc:
        logger.error("LLM streaming error for request %s: %s", request_id, exc)
        yield format_sse({"error": "LLM streaming failed. Please try again."})
        return  # Do NOT persist incomplete response.

    # ── 7. Send done event with citations ─────────────────────────────────────
    citations = extract_citations(selected_chunks)
    yield format_sse({"done": True, "citations": citations})

    # ── 8. Persist user message + assistant response ──────────────────────────
    full_response = "".join(full_response_parts)
    try:
        await append_message(conversation, MessageRole.user, query, None, db)
        await append_message(
            conversation, MessageRole.assistant, full_response, citations, db
        )
    except Exception as exc:
        # The stream was already delivered; log and move on.  The client can
        # resubmit if persistence is critical.
        logger.error(
            "Failed to persist messages for conversation %s: %s",
            conversation.id,
            exc,
        )
